### ISSUE TITLE
Is「Explaine」typo?

### ISSUE THREAD

**Issue by hnts** [rueyaa332266/ezcron#1]
「Explaine」function exist in translator.go.
Is this function name typo? 
https://github.com/rueyaa332266/ezcron/blob/master/translator/translator.go#L167

**Comment by rueyaa332266** [comment]
Thank for your issue report.
It's exactly a typo.
I fix it in this commit.
https://github.com/rueyaa332266/ezcron/commit/289a52aabc9cc16dfcafbd625db43d20e908d6cc
